name: test
on:
    push:
        tags:
            - v*
        branches:
            - master
            - staging
            - dev
    pull_request:

jobs:
    test:
        name: go test
        runs-on: ubuntu-latest
        # env:
        #     GOPRIVATE: "dev.freespoke.com,github.com/Freespoke"
        steps:
            # - name: Configure git for private modules
            #   env:
            #       TOKEN: ${{ secrets.BOT_TOKEN }}
            #       USERNAME: ${{ secrets.BOT_USERNAME }}
            #   run: git config --global url."https://${USERNAME}:${TOKEN}@github.com".insteadOf "https://github.com"

            - uses: actions/checkout@v3

            - uses: actions/setup-go@v4
              with:
                  go-version-file: "./go.mod"
                  cache: true

            - name: Set up gotestfmt
              uses: haveyoudebuggedit/gotestfmt-action@v2
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}

            - name: Run tests
              run: |
                  set -euo pipefail
                  go test -json -v ./... 2>&1 | tee /tmp/gotest.log | gotestfmt
